# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fulltext_searchable}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mitsuhiro Shibuya"]
  s.date = %q{2011-02-15}
  s.description = %q{Rails plugin for fulltext-search by mroonga}
  s.email = %q{shibuya@lavan7.co.jp}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "app/models/fulltext_index.rb",
    "lib/fulltext_searchable.rb",
    "lib/fulltext_searchable/active_record.rb",
    "lib/fulltext_searchable/engine.rb",
    "lib/rails/generators/fulltext_searchable/fulltext_searchable_generator.rb",
    "lib/rails/generators/fulltext_searchable/templates/initializer.rb",
    "lib/rails/generators/fulltext_searchable/templates/migration.rb",
    "lib/rails/generators/fulltext_searchable/templates/schema.rb",
    "lib/tasks/fulltext_searchable.rake"
  ]
  s.homepage = %q{http://git.dev.ist-corp.jp/fulltext_searchable}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails plugin for fulltext-search by mroonga}
  s.test_files = [
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/models/blog.rb",
    "spec/dummy/app/models/comment.rb",
    "spec/dummy/app/models/news.rb",
    "spec/dummy/app/models/reply.rb",
    "spec/dummy/app/models/user.rb",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/fulltext_searchable.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/20110119090740_create_blogs.rb",
    "spec/dummy/db/migrate/20110119090753_create_news.rb",
    "spec/dummy/db/migrate/20110124031824_create_users.rb",
    "spec/dummy/db/migrate/20110203091209_create_comments.rb",
    "spec/dummy/db/migrate/20110215091428_create_fulltext_indices_table.rb",
    "spec/fulltext_searchable_spec.rb",
    "spec/integration/navigation_spec.rb",
    "spec/models/blog_spec.rb",
    "spec/models/comment_spec.rb",
    "spec/models/fulltext_index_spec.rb",
    "spec/models/news_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/factories/blogs.rb",
    "spec/support/factories/comments.rb",
    "spec/support/factories/news.rb",
    "spec/support/factories/users.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0"])
      s.add_runtime_dependency(%q<htmlentities>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.0.0.beta"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<faker>, [">= 0"])
      s.add_development_dependency(%q<cover_me>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.0.0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<will_paginate>, [">= 0"])
      s.add_development_dependency(%q<rails3_acts_as_paranoid>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<htmlentities>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.0.beta"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<cover_me>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 3.0.0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<will_paginate>, [">= 0"])
      s.add_dependency(%q<rails3_acts_as_paranoid>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<htmlentities>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.0.beta"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<cover_me>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 3.0.0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<will_paginate>, [">= 0"])
    s.add_dependency(%q<rails3_acts_as_paranoid>, [">= 0"])
  end
end

